apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: git-clone
  namespace: tekton-app
spec:
  params:
    - name: url
      description: "URL del repositorio Git"
    - name: revision
      description: "Rama o commit del repositorio"
      default: "main"
  workspaces:
    - name: output
      description: "Directorio donde se clonará el repositorio"
  steps:
    - name: clean-workspace
      image: alpine
      script: |
        #!/bin/sh
        rm -rf $(workspaces.output.path)/*
    - name: clone
      image: alpine/git
      script: |
        #!/bin/sh
        git clone $(params.url) -b $(params.revision) $(workspaces.output.path)
