apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: deploy-task
  namespace: tekton-pipelines
spec:
  steps:
    - name: kubectl-apply
      image: bitnami/kubectl:latest
      script: |
        #!/bin/sh
        kubectl apply -f k8s/
