apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: build-deploy-pipeline
spec:
  workspaces:
    - name: shared-workspace
    - name: dockerconfig
  tasks:
    - name: git-clone
      taskRef:
        name: git-clone
      workspaces:
        - name: output
          workspace: shared-workspace
      params:
        - name: url
          value: https://github.com/dshectorjojoa/k8s-app-demo-ds.git
        - name: revision
          value: main
    - name: build-push-api
      runAfter: ["git-clone"]
      taskRef:
        name: kaniko
      workspaces:
        - name: source
          workspace: shared-workspace
        - name: dockerconfig
          workspace: dockerconfig
      params:
        - name: IMAGE
          value: dshectorjojoa/api:latest
        - name: CONTEXT
          value: "api"
        - name: DOCKERFILE
          value: "api/Dockerfile"
    - name: build-push-frontend
      runAfter: ["git-clone"]
      taskRef:
        name: kaniko
      workspaces:
        - name: source
          workspace: shared-workspace
        - name: dockerconfig
          workspace: dockerconfig
      params:
        - name: IMAGE
          value: dshectorjojoa/frontend:latest
        - name: CONTEXT
          value: "frontend"
        - name: DOCKERFILE
          value: "frontend/Dockerfile"