apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: build-deploy-pipeline
spec:
  tasks:
    - name: git-clone
      taskRef:
        name: git-clone
    - name: build-push-api
      runAfter: ["git-clone"]
      taskRef:
        name: kaniko
      params:
        - name: IMAGE
          value: dshectorjojoa/api:latest
    - name: build-push-frontend
      runAfter: ["git-clone"]
      taskRef:
        name: kaniko
      params:
        - name: IMAGE
          value: dshectorjojoa/frontend:latest