apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: k8s-app-demo-ds
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/dshectorjojoa/k8s-app-demo-ds.git' # Cambia esto por tu repositorio
    targetRevision: HEAD
    path: k8s
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
