apiVersion: apps/v1
kind: Deployment
metadata:
  name: hola-mundo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hola-mundo
  template:
    metadata:
      labels:
        app: hola-mundo
    spec:
      containers:
        - name: nginx
          image: dshectorjojoa/hola-mundo:latest
          ports:
            - containerPort: 80
      imagePullSecrets:
        - name: regcred
