apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: build-and-deploy
  namespace: default
spec:
  workspaces:
    - name: shared-workspace
    - name: dockerconfig
  tasks:
    - name: clone-repo
      taskRef:
        name: git-clone
        kind: ClusterTask
      params:
        - name: url
          value: "https://github.com/dshectorjojoa/k8s-app-demo-ds.git"
        - name: revision
          value: "main"
        - name: deleteExisting  # Evita que se borren archivos previos
          value: "false"
      workspaces:
        - name: output
          workspace: shared-workspace

    - name: build-docker
      runAfter:
        - clone-repo  # Asegurar que `clone-repo` termine antes de `build-docker`
      taskRef:
        name: buildah
        kind: ClusterTask
      params:
        - name: IMAGE
          value: "docker.io/dshectorjojoa/hola-mundo:latest"
        - name: STORAGE_DRIVER
          value: "vfs"
        - name: CONTEXT
          value: "/workspace/shared-workspace"  # Asegurar que apunta al workspace correcto
        - name: DOCKERFILE
          value: "docker/Dockerfile"
      workspaces:
        - name: source
          workspace: shared-workspace
        - name: dockerconfig
          workspace: dockerconfig

    - name: push-docker
      runAfter:
        - build-docker  # Asegurar que `build-docker` termine antes de `push-docker`
      taskRef:
        name: buildah
        kind: ClusterTask
      params:
        - name: IMAGE
          value: "docker.io/dshectorjojoa/hola-mundo:latest"
        - name: STORAGE_DRIVER
          value: "vfs"
        - name: CONTEXT
          value: "/workspace/shared-workspace"
        - name: DOCKERFILE
          value: "docker/Dockerfile"
      workspaces:
        - name: source
          workspace: shared-workspace
        - name: dockerconfig
          workspace: dockerconfig
