apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  name: build-and-deploy-run
  namespace: default
spec:
  pipelineRef:
    name: build-and-deploy
  workspaces:
    - name: output  # Usa el PVC en lugar de `emptyDir`
      persistentVolumeClaim:
        claimName: tekton-workspace-pvc
    - name: dockerconfig
      secret:
        secretName: regcred
