apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  name: build-and-deploy-run
  namespace: default
spec:
  pipelineRef:
    name: build-and-deploy
  workspaces:
    - name: output  # Antes: shared-workspace
      emptyDir: {}  # Volumen compartido entre todas las tareas
    - name: dockerconfig
      secret:
        secretName: regcred
