apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  name: build-and-deploy-run
spec:
  pipelineRef:
    name: build-and-deploy
  workspaces:
    - name: shared-workspace
      emptyDir: {}
    - name: docker-auth
      secret:
        secretName: regcred
