apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: build-and-deploy
  namespace: default
spec:
  workspaces:
    - name: output  # Ahora usa un PVC en lugar de un `emptyDir`
    - name: dockerconfig
  tasks:
    - name: clone-repo
      taskRef:
        name: git-clone
        kind: ClusterTask
      params:
        - name: url
          value: "https://github.com/dshectorjojoa/k8s-app-demo-ds.git"
        - name: revision
          value: "main"
      workspaces:
        - name: output
          workspace: output  # Mantener el mismo nombre en todas las tareas

    - name: build-docker
      runAfter:
        - clone-repo
      taskRef:
        name: buildah
        kind: ClusterTask
      params:
        - name: IMAGE
          value: "docker.io/dshectorjojoa/hola-mundo:latest"
        - name: STORAGE_DRIVER
          value: "vfs"
        - name: CONTEXT
          value: "/workspace/output"  # Usar la misma ruta
        - name: DOCKERFILE
          value: "Dockerfile"
      workspaces:
        - name: source
          workspace: output  # Antes: shared-workspace
        - name: dockerconfig
          workspace: dockerconfig

    - name: push-docker
      runAfter:
        - build-docker
      taskRef:
        name: buildah
        kind: ClusterTask
      params:
        - name: IMAGE
          value: "docker.io/dshectorjojoa/hola-mundo:latest"
        - name: STORAGE_DRIVER
          value: "vfs"
        - name: CONTEXT
          value: "/workspace/output"
        - name: DOCKERFILE
          value: "Dockerfile"
      workspaces:
        - name: source
          workspace: output
        - name: dockerconfig
          workspace: dockerconfig
